### ISSUE TITLE
Long navigation entries don't fit in dropdown container

### ISSUE THREAD

**Issue by aepp** [t3kit/theme_t3kit#246]
Like here:
![width100](https://user-images.githubusercontent.com/5745874/27533739-00ccc448-5a65-11e7-8f05-06cdf3ac1dbe.png)

long words without hyphens don't fit in the navigation list if the container width is set to 100%.

If it's set to auto - it looks better:

![width_auto](https://user-images.githubusercontent.com/5745874/27533738-00cc2196-5a65-11e7-9920-9a872d91824b.png)

The corresponding CSS line:

```css
.main-navigation__sub-item-list {
    ...
    width: 100%;
    ...
}
```

in `theme_t3kit/Resources/Public/felayout_t3kit/main.less`
