### ISSUE TITLE
Global button styles

### ISSUE THREAD

**Issue by aennafae** [t3kit/theme_t3kit#329]
What do you think to have constants for button styles e.q.
```
themes.configuration.less.var.buttonTextColor =
themes.configuration.less.var.buttonBgColor =
```
These styles will go to **.btn-primary**

```
@btn-primary-color:             @button-text-color;
@btn-primary-bg:                 @button-bg-color;
@btn-primary-border:           @button-bg-color;
```
From this we can define four different button styles, that will work on different backgrounds
```less
.btn-primary {
  color: @btn-primary-color;
  background-color: @btn-primary-bg;
  border-color: @btn-primary-border;
}
.btn-primary--inverted {
  color: @btn-primary-bg;
  background-color: @btn-primary-color;
  border-color: @btn-primary-color;
}
.btn-secondary {
  color: @btn-primary-bg;
  background-color: transparent;
  border-color: @btn-primary-bg;
}
.btn-secondary--inverted {
  color:@btn-primary-color;
  background-color: transparent;
  border-color: @btn-primary-color;
}
```

Further I would suggest to style the hover with same colors by only darken them.
```css
.btn-primary:hover {
  background-color: darken(@btn-primary-bg, 10%)
  border-color: darken(@btn-primary-bg, 10%)
}
```
We would only use the four classes to style all buttons. Except if there should be a complete different colored button.

t3kit.com
![blue-button](https://user-images.githubusercontent.com/6085021/32176270-7cb62268-bd87-11e7-9bb8-8ab481644cdf.png)
t3quick.de
![green-button](https://user-images.githubusercontent.com/6085021/32176269-7c97ef0a-bd87-11e7-91fc-4f1539698914.png)
